server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://193.112.65.251:3307/zqplayer?useSSL=false
    username: root
    password: zaiqiang

mybatis:
  mapper-locations: classpath:mybatis_starter/mapper/*.xml
  config-location: classpath:mybatis_starter/config.xml

zqconfig: #自定义配置
  author: zaiqiang333

