version: "3"
services:
  zqplayer:
    image: docker.io/ziq358/zqplayer:v1
    ports:
      - 1234:6666
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - zqplayernet
networks:
  zqplayernet: